task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

num_classes: 2
remap_mscoco_category: False


train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /home/ubuntu/data_split_85_15/train/images
    ann_file: /home/ubuntu/data_split_85_15/annotations/train.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 8
  drop_last: True 
  collate_fn:
    type: BatchImageCollateFuncion


val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /home/ubuntu/data_split_85_15/val/images
    ann_file: /home/ubuntu/data_split_85_15/annotations/val.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~ 
  shuffle: False
  num_workers: 8
  drop_last: False
  collate_fn:
    type: BatchImageCollateFuncion
